name: chats
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_lints: ^2.0.0
  get: 4.1.4

  firebase_core: ^1.6.0
  firebase_auth: ^3.3.20
  cloud_firestore: ^3.1.17
  firebase_storage: 9.0.0

  google_sign_in: 5.0.4
  lottie: 1.1.0
  introduction_screen: 2.1.0
  avatar_glow: 2.0.1
  emoji_picker_flutter: 1.0.6
  get_storage: 2.0.3
  intl: 0.17.0
  image_picker: 0.8.3+2
  smooth_page_indicator: ^1.0.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.9.1"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo/icon.png"

flutter:
  assets:
    - assets/lottie/
    - assets/logo/
  uses-material-design: true

